# https://velog.io/@hind_sight/Docker-Jenkins-%EB%8F%84%EC%BB%A4%EC%99%80-%EC%A0%A0%ED%82%A8%EC%8A%A4%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-Spring-Boot-CICD
# https://devops4solutions.com/ci-cd-using-jenkins-and-docker-2/
# https://www.jenkins.io/doc/book/pipeline/docker/

FROM jenkins/jenkins:jdk11